[package]
name = "niamc"
version = "0.1.0"
edition = "2024"

[dependencies]
lexer = { path = "../lexer" }
common = { path = "../common" }
parser = { path = "../parser" }
ariadne = { version = "0.6.0", features = ["auto-color"] }
argh = { version = "0.1.13" }

